# Generated by Django 5.1.5 on 2025-07-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clockin_clockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
